#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 	2
bspc config window_gap 		12

bspc config split_ratio 	0.50
bspc config borderless_monocle 	true
bspc config gapless_monocle 	true

# Example bspc rule
# bspc rule -a Gimp desktop='^8' state=floating follow=on

# Launch Polybar (and a few other things...)
picom &
$HOME/.config/polybar/launch.sh --material
feh --bg-fill $HOME/.config/wallpapers/hexagons.jpg
