#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 	2
bspc config window_gap 		12

bspc config split_ratio 	0.50
bspc config borderless_monocle 	true
bspc config gapless_monocle 	true

# Some basic Dracula colors
# https://draculatheme.com/bspwm
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# Example bspc rule
# bspc rule -a Gimp desktop='^8' state=floating follow=on

# Launch Polybar (and a few other things...)
picom &
$HOME/.config/polybar/launch.sh --material
feh --bg-fill $HOME/.config/wallpapers/breath-of-the-wild.jpg

